// Code generated by ChatGPT
// code to style certain phrases in the text
document.addEventListener("DOMContentLoaded", () => {
    const phrases = {
        "[DATA EXPUNGED]": "<strong><span style='color: red;'>[DATA EXPUNGED]</span></strong>" // Style for [DATA EXPUNGED]
       
    };
    const Htypes={
        "Safe": "<strong><span style='color: green;'>Safe</span></strong>", // Style for Safe
        "Euclid": "<strong><span style='color: orange;'>Euclid</span></strong>" // Style for Euclid
    };
    // Function to replace phrases in a given element's text content
    const styleText = (element) => {
        for (let phrase in phrases) {
            element.innerHTML = element.innerHTML.split(phrase).join(phrases[phrase]);
        }
    };
    const styleHeadings = (element) => {
        for (let phrase in Htypes) {
            element.innerHTML = element.innerHTML.split(phrase).join(Htypes[phrase]);
        }
    };
    // Apply the styling to <p> tags
    document.querySelectorAll("p").forEach(p => {
        styleText(p);
    });

    // Apply the styling to <code> tags
    document.querySelectorAll("code").forEach(code => {
        styleText(code);
    });
    // Apply the styling to <code> tags
    document.querySelectorAll("h2").forEach(h2 => {
        styleHeadings(h2);
    });
});
